### ISSUE TITLE
Connect Error

### ISSUE THREAD

**Issue by dramabeats** [dramabeats/Ruby-Parse#1]
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:319:in `open_http'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:737:in `buffer_open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:212:in `block in open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `catch'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:210:in `open_loop'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:151:in `open_uri'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:717:in `open'
        from C:/Ruby23-x64/lib/ruby/2.3.0/open-uri.rb:35:in `open'
        from parse.rb:4:in `<main>'

**Comment by dramabeats** [comment]
https://github.com/liveeditor/net_http_ssl_fix

Net HTTP SSL is broken on windows

**Comment by dramabeats** [comment]
Resolved commit #c1a62a46a7d1a205707f194426888cf58e6bf376

Removed S from HTTP
